In [1]:
#NumPy Exercises

1. Replace all odd numbers in the given array with -1
-> Generate array of range 10
-> Replace odd number with -1

2. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
-> go through methods of np.random

3. Extract the first four columns of this 2-D array
-> Generate array with `np.arange(100).reshape(5,-1)`
-> extract first four columns of each row

4. Compare two arrays:
-> create two 1D arrays of any equal range
-> get elements in x where its value is more than its corresponding element in y,
-> get elements in x where its value is equals to its corresponding element in y.

5. Create a 3x3x3 array with random values
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Multiply a 5x3 matrix by a 3x2 matrix
9. convert a float (32 bits) array into an integer (32 bits)
10. Extract items from array
-> input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
-> expected output: array([1, 3, 5, 7, 9])
11. Get common items betweeen two array
input :
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

output:
array([2, 4])

In [2]:
import numpy as np

In [16]:
#1  Replace all odd numbers in the given array with -1
#-> Generate array of range 10
#-> Replace odd number with -1

arr = np.arange(0,10)
arr[arr%2 != 0 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [31]:
#2  Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
#-> go through methods of np.random

np.random.randint(30,40,(10,10))

array([[33, 37, 38, 35, 31, 39, 36, 38, 30, 39],
       [39, 30, 30, 34, 34, 32, 32, 36, 39, 33],
       [32, 30, 33, 30, 32, 34, 30, 37, 36, 32],
       [37, 39, 35, 35, 35, 36, 35, 32, 39, 35],
       [31, 36, 30, 35, 36, 37, 36, 38, 38, 39],
       [38, 35, 38, 33, 33, 30, 35, 32, 33, 33],
       [37, 34, 34, 32, 34, 38, 39, 38, 32, 31],
       [39, 33, 35, 39, 30, 37, 39, 34, 34, 39],
       [37, 30, 39, 39, 33, 34, 30, 38, 32, 30],
       [34, 31, 31, 33, 31, 34, 32, 38, 33, 33]])

In [32]:
#3 Extract the first four columns of this 2-D array
#-> Generate array with `np.arange(100).reshape(5,-1)`
#-> extract first four columns of each row

arr1 = np.arange(100).reshape(5,-1)

In [33]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [34]:
arr1[ : , :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [45]:
#4 4. Compare two arrays:
#-> create two 1D arrays of any equal range
#-> get elements in x where its value is more than its corresponding element in y,
#-> get elements in x where its value is equals to its corresponding element in y.


x = np.random.rand(30)
y = np.random.rand(30)


In [46]:
x

array([0.69837579, 0.9880824 , 0.85769818, 0.6560138 , 0.78575613,
       0.69223331, 0.10271446, 0.4815832 , 0.70223389, 0.89383644,
       0.13282742, 0.3080501 , 0.79937961, 0.48728907, 0.00459649,
       0.06580684, 0.98321386, 0.62710016, 0.66834621, 0.82661151,
       0.28023618, 0.45577188, 0.80836919, 0.18800007, 0.99813144,
       0.24914943, 0.94471042, 0.83050395, 0.33762371, 0.29987969])

In [47]:
y

array([0.3787679 , 0.81199509, 0.39854501, 0.01593465, 0.13340693,
       0.73988343, 0.92639732, 0.04200154, 0.41422358, 0.83096701,
       0.99334084, 0.37284798, 0.20777282, 0.91859501, 0.9114434 ,
       0.3095606 , 0.86922836, 0.46418159, 0.41441099, 0.95013999,
       0.77357468, 0.65230036, 0.5973876 , 0.93519839, 0.78788845,
       0.10687117, 0.65341306, 0.41087194, 0.01044253, 0.67724308])

In [48]:
x[x>y]

array([0.69837579, 0.9880824 , 0.85769818, 0.6560138 , 0.78575613,
       0.4815832 , 0.70223389, 0.89383644, 0.79937961, 0.98321386,
       0.62710016, 0.66834621, 0.80836919, 0.99813144, 0.24914943,
       0.94471042, 0.83050395, 0.33762371])

In [51]:
x[x==y]

array([], dtype=float64)

In [54]:
#5 Create a 3x3x3 array with random values

arr2 = np.random.randn(3,3,3)
arr2

array([[[-1.22812801, -1.43317311, -0.94857378],
        [ 1.82953822,  0.41463677, -2.11769867],
        [-0.4713792 , -0.60967698, -2.16599048]],

       [[ 0.57816736,  0.07138648,  0.2217002 ],
        [ 0.48377623, -0.61695823,  0.21025213],
        [-1.73419333,  0.08087198,  0.53084761]],

       [[-0.62759224, -0.46559972, -0.60981607],
        [ 0.83205374, -0.85757509, -1.52810018],
        [-0.38011396,  0.19956594,  0.60882065]]])

In [57]:
#6 Create a 10x10 array with random values and find the minimum and maximum values

arr3 = np.random.randint(20,80, (10,10))
arr3

array([[31, 54, 58, 60, 51, 22, 57, 34, 47, 36],
       [69, 78, 62, 30, 49, 28, 28, 72, 43, 76],
       [78, 68, 48, 72, 33, 50, 32, 32, 72, 67],
       [43, 48, 26, 53, 26, 41, 30, 53, 34, 64],
       [67, 50, 62, 58, 34, 61, 63, 73, 52, 21],
       [39, 57, 53, 75, 48, 76, 23, 49, 77, 50],
       [76, 45, 27, 64, 63, 56, 74, 21, 29, 34],
       [54, 46, 25, 66, 44, 53, 25, 25, 49, 59],
       [70, 77, 37, 48, 58, 76, 63, 70, 48, 44],
       [25, 42, 33, 25, 73, 36, 21, 27, 43, 45]])

In [60]:
arr3.max()

78

In [61]:
arr3.min()

21

In [76]:
#7 Create a random vector of size 30 and find the mean value

vec = np.random.randint((10), size=(30))

In [78]:
vec

array([7, 6, 2, 1, 0, 8, 8, 8, 7, 5, 0, 9, 0, 5, 3, 6, 0, 6, 3, 2, 6, 4,
       5, 6, 6, 3, 7, 7, 3, 6])

In [79]:
vec.mean()

4.633333333333334

In [80]:
#8 Multiply a 5x3 matrix by a 3x2 matrix

a = np.random.randint(4,8, (5,3))
b = np.random.randint(4,8, (3,2))

In [81]:
a@b          #Matrix multiplication

array([[ 68,  60],
       [101,  87],
       [108,  96],
       [ 87,  77],
       [ 94,  86]])

In [90]:
#9 convert a float (32 bits) array into an integer (32 bits)

t = np.array([2, 9.6 , 8.7 , 9 , 3.7], dtype = int)

In [92]:
t

array([2, 9, 8, 9, 3])

In [94]:
type(t[2])

numpy.int32

In [95]:
#10 Extract items from array
#-> input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#-> expected output: array([1, 3, 5, 7, 9])

In [97]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0]

array([1, 3, 5, 7, 9])

In [102]:
#11. Get common items betweeen two array
#input :

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


#output:
#array([2, 4])

c = np.intersect1d(a, b)
c

array([2, 4])