In [1]:
#NumPy: Short for numerical Python 

#ndarray: Efficient multidimensional array providing fast array oriented arithmatic operations 
#and flexible broadcasting capabilities
#nd arrays is a generic multidimensional container for homogenous data
#Every array has  a shape, a tuple indicating the size of each dimension and a dtype an object describing data type of the array. 


#Mathematical functions for fast operations on entire arrays of data without writing loops

#NumPy by itself doesnot provide modelling or scientific functionality but it uses tools with array oriented semantics like Pandas


In [2]:
#PIP: Python Package Manager

#Stands for Preffered Installer Program

#Pip is one of the most widely used package management system to install and manage software packages
#written in Python and found in Python Package index (PyPI)
#Pip has recursive acronym that stands for "Pip Installs Packeges" or "Pip installs Python"

#pip install 'Package name'

In [3]:
#Creating ndarrays

In [4]:
import numpy as np
data = [1,2,3,4]

In [5]:
arr = np.array(data)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.shape

(4,)

In [8]:
d2 = [[1,2,3,4], [6,7,8,9]]

In [9]:
arr1 = np.array(d2)

In [10]:
arr1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [11]:
arr1.shape

(2, 4)

In [12]:
arr1.ndim

2

In [13]:
arr1.dtype

dtype('int32')

In [14]:
#Other ways to create ndarrays

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.empty((3,3,2))   #columns, rows, sets

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
#arange: An array values version of built in Python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
#Data types for ndarrays

#dtypes are very powerful and flexible 

In [23]:
ar = np.array([1,2,3,4], dtype=np.float64)

In [24]:
ar

array([1., 2., 3., 4.])

In [25]:
# astype: To convert or cast as an array from 1 dtype to another

In [26]:
arr = np.array([1,2,3,4,5])

In [27]:
arr.dtype

dtype('int32')

In [30]:
arrflo = arr.astype(np.float64)

In [31]:
arrflo

array([1., 2., 3., 4., 5.])

In [32]:
#Mathematical operations on array

In [34]:
arr = np.array([[1,2,3,4], [5,5,6,9]])

In [35]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 25, 36, 81]])

In [36]:
1/arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.2       , 0.16666667, 0.11111111]])

In [37]:
arr*10

array([[10, 20, 30, 40],
       [50, 50, 60, 90]])

In [38]:
#Indexing and slicing

In [45]:
arr = np.arange(1,10)

In [46]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5]

6

In [48]:
arr[5:8]

array([6, 7, 8])

In [51]:
#Broadcasting
arr[5:8] = 12

In [52]:
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9])

In [53]:
#Array slices are views on the original array
#If data is not copied and any changes to the view will be reflected in source array

In [60]:
arr_slice = arr[5:8]

In [61]:
arr_slice

array([64, 64, 64])

In [62]:
arr_slice[1] = 12345

In [63]:
arr_slice

array([   64, 12345,    64])

In [64]:
arr_slice[:] = 64

In [65]:
arr_slice

array([64, 64, 64])

In [ ]:
#With higher dim arrays we have many more options. 

#In 2D arrays, the elements at each index are no longer scalars but rather one dim arrays

In [66]:
arr2d = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [67]:
arr2d[2]

array([6, 7, 8])

In [69]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [70]:
arr2d[0,2]   #row,column

3

In [71]:
#Indexing with slices 

In [73]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [74]:
arr2d[2:, :1]

array([[6]])

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [90]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [6, 7]])

In [101]:
arr2d[1, 0:2]

array([4, 5])

In [103]:
arr2d[2, 1]

7

In [105]:
arr2d[1:, 1:]

array([[5, 6],
       [7, 8]])

In [107]:
arr2d[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [108]:
#Boolean Indexing

In [279]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Gen'])

In [280]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Gen'], dtype='<U4')

In [281]:
data = np.random.randn(7,4)

In [282]:
data

array([[ 2.11315736,  1.26522292,  1.90087365,  1.74601205],
       [-0.48713339,  0.50557794,  0.11939746, -0.27639106],
       [ 0.27778155,  0.71610879, -1.25744461,  0.21079892],
       [ 0.17099365,  0.80152419, -0.36026308, -1.36831976],
       [ 0.57347065,  1.621978  , -0.42366268, -0.06701857],
       [-0.34516359, -0.85773698,  0.97856731, -0.55649648],
       [ 0.52656978,  0.67544906, -0.75097855, -2.11733234]])

In [283]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [284]:
data[names == 'Bob']

array([[ 2.11315736,  1.26522292,  1.90087365,  1.74601205],
       [ 0.17099365,  0.80152419, -0.36026308, -1.36831976]])

In [285]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [286]:
data[(names != 'Bob')]

array([[-0.48713339,  0.50557794,  0.11939746, -0.27639106],
       [ 0.27778155,  0.71610879, -1.25744461,  0.21079892],
       [ 0.57347065,  1.621978  , -0.42366268, -0.06701857],
       [-0.34516359, -0.85773698,  0.97856731, -0.55649648],
       [ 0.52656978,  0.67544906, -0.75097855, -2.11733234]])

In [287]:
data[~(names == 'Bob')]

array([[-0.48713339,  0.50557794,  0.11939746, -0.27639106],
       [ 0.27778155,  0.71610879, -1.25744461,  0.21079892],
       [ 0.57347065,  1.621978  , -0.42366268, -0.06701857],
       [-0.34516359, -0.85773698,  0.97856731, -0.55649648],
       [ 0.52656978,  0.67544906, -0.75097855, -2.11733234]])

In [24]:
a = np.arange(12).reshape(3,4)

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
b = a>4

In [130]:
b  #Boolean array for array a

#True: elements which follow the condition
#False: Elements which do not follow the condition 

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [131]:
a[b]        #b is the index & it will only return the elemnts that follow 

array([ 5,  6,  7,  8,  9, 10, 11])

In [134]:
a[b] = -1   #will replace true elemnts with -1

In [135]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [137]:
mask = (names == 'Bob') | (names == 'will')


In [138]:
data[mask]

array([[ 1.00288998,  0.64501129,  1.07177543, -1.58778301],
       [-0.29497589, -0.44532254,  1.42048791, -0.08334918]])

In [140]:
data[mask] = 0

In [141]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.97167567,  1.26915747,  0.86367455, -1.33638853],
       [-1.73975567, -0.7674566 , -0.70085282, -0.26969908],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.1076189 ,  0.04536024, -1.39022727, -1.80290342],
       [ 1.08779142, -1.37490079, -1.53925837, -2.0696741 ],
       [-1.2287421 ,  1.58695829,  0.4455114 , -0.15913918]])

In [142]:
#Fancy Indexing

In [143]:
arr = np.array([
    [ 0., 0., 0., 0.],
    [ 1., 1., 1., 1.],
    [ 2., 2., 2., 2.],
    [ 3., 3., 3., 3.],
    [ 4., 4., 4., 4.],
    [ 5., 5., 5., 5.],
    [ 6., 6., 6., 6.],
    [ 7., 7., 7., 7.] 
])

In [144]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [145]:
arr = np.arange(32).reshape((8,4))

In [147]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [148]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
arr[[1,5,7,2], [0,3,1,2]]     #arr[[row indexes], [column indexes corresponding to row indexes]]

array([ 4, 23, 29, 10])

In [156]:
arr[[1,5,7,2]] [:, [0,3,1,2]]  #can be used to rearrange array

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [157]:
arr[[1,5,7,2]] 

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [158]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [159]:
#Transposing Arrays and swapping axes

In [160]:
arr = np.arange(15).reshape((3,5))

In [161]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [162]:

arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [168]:
arr= np.random.randn(6,3)

In [169]:
arr

array([[ 0.85128347, -0.38699041,  1.5200009 ],
       [-2.22362618,  0.57676498,  1.1394046 ],
       [ 0.28917472,  0.03452035, -0.25567186],
       [-0.50776817, -1.24328701,  0.67093058],
       [-1.15768191, -1.14412064,  0.97640541],
       [ 1.6414046 ,  1.34689339,  0.24714863]])

In [170]:
arr.T

array([[ 0.85128347, -2.22362618,  0.28917472, -0.50776817, -1.15768191,
         1.6414046 ],
       [-0.38699041,  0.57676498,  0.03452035, -1.24328701, -1.14412064,
         1.34689339],
       [ 1.5200009 ,  1.1394046 , -0.25567186,  0.67093058,  0.97640541,
         0.24714863]])

In [171]:
np.dot(arr.T, arr)

array([[10.04508395,  2.56466052, -2.37896527],
       [ 2.56466052,  5.1525075 , -1.55828499],
       [-2.37896527, -1.55828499,  5.13861148]])

In [173]:
#Element wise array functions

In [174]:
arr = np.arange(10)

In [175]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [177]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [184]:
y = np.random.randn(8)
x = np.random.randn(8)

In [185]:
y

array([-0.23777145,  0.7590379 , -0.26437522, -0.70876225, -1.41879602,
        1.58743486,  2.0620682 , -0.94151837])

In [186]:
x

array([ 0.91042437,  0.10844955,  1.41459602,  2.05623948,  0.33864434,
       -2.50938279,  0.72158587,  0.89323245])

In [187]:
np.maximum(x,y)

array([0.91042437, 0.7590379 , 1.41459602, 2.05623948, 0.33864434,
       1.58743486, 2.0620682 , 0.89323245])

In [188]:
#Conditional logic as array operations

In [189]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

cond = np.array([True, False, True, True, False])

In [190]:
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]

In [191]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [192]:
result = np.where(cond, xarr, yarr)

In [193]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [195]:
arr = np.random.randn(4, 4)

In [196]:
arr

array([[-0.85544156,  0.90302065, -1.37171743,  0.5792667 ],
       [-0.07988804,  0.50755374,  0.24769247, -1.0570542 ],
       [-0.9048824 , -0.58196302,  0.79804478,  1.14396864],
       [-0.05592908, -0.63977559,  0.73842642,  1.26914367]])

In [197]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [-2,  2,  2, -2],
       [-2, -2,  2,  2],
       [-2, -2,  2,  2]])

In [198]:
np.where(arr > 0, 2, arr)

array([[-0.85544156,  2.        , -1.37171743,  2.        ],
       [-0.07988804,  2.        ,  2.        , -1.0570542 ],
       [-0.9048824 , -0.58196302,  2.        ,  2.        ],
       [-0.05592908, -0.63977559,  2.        ,  2.        ]])

In [199]:
#Nested Condition 

In [208]:
cond1 = np.array([True, True, False, True])
cond2 = np.array([False, True, True, False])

result = []

for i in range(4):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [209]:
result

[1, 0, 2, 1]

In [210]:
np.where(cond1 & cond2, 0,
        np.where(cond1, 1,
                np.where(cond2, 2, 3)))

array([1, 0, 2, 1])

In [211]:
#Mathematical operations

In [213]:
arr = np.random.randn(5,4)

In [214]:
arr

array([[ 1.17113872,  0.39365498, -0.05549068, -0.7114396 ],
       [-0.80274173,  0.05749616, -1.57500646,  1.12456421],
       [ 0.06159953, -0.70001265, -0.54875982,  0.48797129],
       [-0.74868202,  1.07417718, -0.53557614,  1.82537484],
       [-0.23617142,  1.84283421,  0.42745764, -0.09243353]])

In [215]:
arr.mean()

0.12299773602438183

In [216]:
arr.sum()

2.4599547204876364

In [218]:
arr.mean(axis = 0)

array([-0.11097138,  0.53362998, -0.45747509,  0.52680744])

In [219]:
arr.sum(0)

array([-0.55485692,  2.66814988, -2.28737545,  2.63403721])

In [222]:
arr.cumsum(axis = 0)

array([[ 1.17113872,  0.39365498, -0.05549068, -0.7114396 ],
       [ 0.36839699,  0.45115114, -1.63049713,  0.41312461],
       [ 0.42999652, -0.24886151, -2.17925695,  0.9010959 ],
       [-0.3186855 ,  0.82531567, -2.71483309,  2.72647074],
       [-0.55485692,  2.66814988, -2.28737545,  2.63403721]])

In [223]:
#Methods for Boolean arrays

In [27]:
arr = np.random.randn(100)

In [28]:
arr

array([ 0.73023838,  0.89751619, -1.26796124, -0.90423049,  0.1765969 ,
       -0.19070246,  0.85749122,  0.22231301, -1.11579381,  0.02190816,
        1.32661377, -0.3002481 , -0.4979243 ,  1.13249805, -0.65769627,
       -1.0708183 , -1.62230135,  2.08844321,  0.13657938, -0.14476526,
        0.51313108,  0.76249626,  0.20164426, -0.12561948,  0.29373091,
       -0.23394226, -0.31927133,  1.4996568 ,  0.27986122,  0.65160661,
        1.07546431,  2.70417724, -0.42256596,  0.57852016, -0.5700499 ,
       -0.25258152,  0.29376425,  0.44021584,  1.16410744,  2.22015985,
       -3.58496163, -0.2055352 ,  1.6103276 ,  0.58032953, -0.81727923,
       -0.22170579, -0.59642228, -1.63652073,  0.99000995, -0.77372199,
        1.05849859, -0.30231936,  0.46024013,  0.55726885, -0.18362108,
        0.1608968 , -0.15065515,  2.75015953, -2.67212737,  2.67619276,
       -0.33312922, -0.52187588,  0.28500183,  0.84138327, -0.21952485,
        0.68586641, -1.23885131, -1.94630994, -0.13442073, -2.12

In [30]:
(arr > 0).sum()

50

In [228]:
arr = np.array([False, False, True, False])

In [231]:
any(arr)

True

In [232]:
all(arr)

False

In [234]:
#Sorting

In [236]:
arr = np.random.randn(8)

In [237]:
arr

array([-0.42463651,  0.41644078, -1.37494586, -0.13467252, -1.68519108,
        1.39664367,  0.06915968, -0.07667946])

In [238]:
arr.sort()

In [246]:
#Unique and Other set logic 

In [249]:
names = np.array(['Bob', 'Bob', 'kal', 'appy', 'kal'])

In [250]:
np.unique(names)

array(['Bob', 'appy', 'kal'], dtype='<U4')

In [251]:
values = np.array([6,0,0,3,2,5,6])

In [252]:
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [253]:
#np.in1d tests the membership of the values of 1 array in the other,
#Returns a boolean array

In [254]:
arr = np.arange(10)

In [255]:
np.save('some_array', arr)

In [256]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [257]:
#To load csv

In [259]:
#np.loadtxt('array_ex.txt', delimiter=',')

In [260]:
#Linear Algebra    (np.linalg): Has a standard set of matrix decompositions and things like inverse and determinant

In [261]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1,7], [8,9]])

x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [262]:
from numpy.linalg import inv, qr

In [263]:
x = np.random.randn(5,5)

In [264]:
x

array([[ 1.51628359,  1.31982148, -0.78700541,  0.27269166, -0.27860276],
       [ 1.06128182,  0.28852232, -0.37784216, -0.12489281, -1.47060511],
       [ 0.50339067,  0.30759398, -0.86111637, -0.01458734,  1.63484036],
       [-2.65739153,  0.34212322,  0.36898546, -0.8598292 ,  0.90876468],
       [ 0.91071499,  0.94323812, -0.28548476,  0.22005765, -1.85467033]])

In [266]:
mat = x.T.dot(x)

In [267]:
mat

array([[11.5699687 ,  2.41213282, -3.26833244,  2.75890093, -5.26422353],
       [ 2.41213282,  2.92653437, -1.55563837,  0.2327822 , -1.7276275 ],
       [-3.26833244, -1.55563837,  1.72131543, -0.53494623,  0.23193177],
       [ 2.75890093,  0.2327822 , -0.53494623,  0.87790338, -1.10566943],
       [-5.26422353, -1.7276275 ,  0.23193177, -1.10566943,  9.17865716]])

inv(mat

In [268]:
#To get inverse of matrix

inv(mat)

array([[  6.34059377,   3.21781034,  11.32536853, -10.48675543,
          2.69275586],
       [  3.21781034,   2.66494855,   6.8735477 ,  -4.58955766,
          1.62056207],
       [ 11.32536853,   6.8735477 ,  22.18743075, -17.43510705,
          5.12828464],
       [-10.48675543,  -4.58955766, -17.43510705,  19.54499022,
         -4.08334428],
       [  2.69275586,   1.62056207,   5.12828464,  -4.08334428,
          1.33687914]])

In [269]:
#To get identity matrix 
mat.dot(inv(mat))

array([[ 1.00000000e+00,  4.61946760e-15,  9.12836597e-15,
        -3.18190775e-15, -1.46928617e-15],
       [ 9.82897628e-16,  1.00000000e+00, -1.22948203e-15,
        -7.38383629e-15, -5.54433136e-16],
       [-1.46899988e-15, -2.33473529e-15,  1.00000000e+00,
         1.15425807e-15,  1.60359182e-15],
       [ 2.32487890e-15,  1.16744752e-15,  1.42960882e-15,
         1.00000000e+00, -1.71042561e-15],
       [ 4.70672474e-17, -6.35415694e-15, -1.37220590e-15,
        -2.51505433e-17,  1.00000000e+00]])